ai_goals:
- efficient localization
- efficient mapping
- accurate localization
- accurate mapping
ai_name: CyberGPT
ai_role: basic robot platform that can do localization and mapping under unknown environments
