default_language_version:
  python: python3.10
repos:

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        stages: [pre-commit]

-   repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: python -m pytest -v tests/
        language: system
        types: [python]
        stages: [pre-push]
        always_run: true