site_name: CYBER
site_description: "A General Robotic Operation System for Embodied AI"

repo_url: ${REPO_URL}
repo_name: ${REPO_NAME}

remote_branch: gh-pages

theme:
    icon:
        repo: fontawesome/brands/github
    name: material
    favicon: imgs/logo_dark.png
    logo: imgs/logo_with_name_dark.png
    palette:
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/brightness-auto
              name: Switch to system preference
        - media: "(prefers-color-scheme: light)"
          primary: "indigo"
          accent: "pink"
          scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: "deep-purple"
          accent: "cyan"
          scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode

plugins:
    - search
    - mkdocstrings
    - search
    - mkdocstrings

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
    - Home: index.md
    - Key Features: features.md
    - Modular Components:
          - World Model: tutorial/world.md
          - Action Model: tutorial/action.md
          - Perception Model: tutorial/preception.md
          - Memory Model: tutorial/memory.md
          - Control Model: tutorial/control.md
    - Setup: setup.md
    - Hugging Face Integration: huggingface.md
    - Usage: experiments/world_model.md
    - File Structure: file_structure.md
    - References: reference.md
    - Contact: contact.md
