name: Documentation

on:
  release:
    types: [created]
  push: # When the main branch is pushed to the GitHub repository
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yaml'
  pull_request: # When a pull request is merged into the main branch
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yaml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPO_TYPE: ${{ secrets.REPO_TYPE }} # Set this secret to 'internal' or 'public'
      INTERNAL_REPO_URL: ttps://github.com/CyberOrigin2077/cyber-internal
      INTERNAL_REPO_NAME: CyberOrigin2077/Cyber-internal
      PUBLIC_REPO_URL: https://github.com/CyberOrigin2077/Cyber
      PUBLIC_REPO_NAME: CyberOrigin2077/Cyber
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r docs/requirements/requirements-doc.txt
      
      - name: Set repo_url and repo_name
        run: |
          if [ "${REPO_TYPE}" = "internal" ]; then
            export REPO_URL=${INTERNAL_REPO_URL}
            export REPO_NAME=${INTERNAL_REPO_NAME}
          else
            export REPO_URL=${PUBLIC_REPO_URL}
            export REPO_NAME=${PUBLIC_REPO_NAME}
          fi
          sed -i "s|\${REPO_URL}|${REPO_URL}|g" mkdocs.yaml
          sed -i "s|\${REPO_NAME}|${REPO_NAME}|g" mkdocs.yaml
      
      - name: Build site
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force
